MPAS-Dev/geometric_features

- README.md
Fixes README and reduces ambiguity.
> Adds requirement for plot_features.py to README

- manipulate_features.py
This merge adds a script which can be used to manipulate feature
definitions, such as inverting a feature or combining multiple features
into a single feature.
> Add manipulate_features.py

- merge_features.py
This merge sorts the files before they are added to the
features.geojson file, and adds some try/except blocks to prevent an
existing valid features.geojson file from being clobbered. If an
existing features.geojson file is not valid, it will be clobbered
however.
> Add sorting, and catch some parsing errors with try blocks

- plot_features.py
This PR cleans up the plotting routine and adds additional projection types
> Additional projection types

- difference_features.py
- fix_features_at_antimeridian.py
- manipulate_features.py
- merge_features.py
- split_features.py
This merge cleans up the python tabs and replaces them with 4 spaces. Additionally, it adds vim modelines to help keep this consistent formatting within the python scripts.
> Cleanup python tabs

- driver_scripts/setup_basins.py
A weird typo crept in to the commit.  Somehow a line of the script got deleted and replaced by a 'd'.
> Fix plotting in setup_basin.py

- driver_scripts/setup_ocean_critical_passages.py
- ocean/transect/Baltic_Sea_Deepen/transect.geojson
- ocean/transect/Persian_Gulf_Deepen/transect.geojson
- ocean/transect/Red_Sea_Deepen/transect.geojson
- ocean/transect/Strait_of_Gibralter_Deepen_1/transect.geojson
- ocean/transect/Strait_of_Gibralter_Deepen_2/transect.geojson
The transects cover:
Denmark Strait
Strait of Gibraltar
Entrance to Red Sea
Entrance to Persian Gulf
> Add transects for critical passages and driver script to merge them

- plot_features.py
This merge used cartopy support for shapely geometries to perform
plotting rather than creating plotting objects ourselves.
Also, plotting properties have been improved so that transects
are not plotted as filled shapes.
The bounds of the plot are computed based on the combined bounding
box of all plotted objects (other than the coastlines).
> Change plotting to use cartopy add_geometries

- utils/feature_write_utils.py
feature properties are placed in an ordered dictionary before
writing.  Keys other than type and groupName in feature collections
are also sorted, as are keys other than type and properties in
individual features.
> Sort properties before writing to geojson

- plot_features.py
Tiny change here to allow plot_features to work without x-forwarding.
> Allow plot_features to produce png files without x-forwarding

- .travis.yml
- ci/install_python.ps1
- ci/requirements-py27.yml
- set_group_name.py
- test/__init__.py
- test/test_set_group_name.py
- utils/feature_test_utils.py
This commit adds Travis CI capability and performs a simple unit test.
> Adds Travis CI and example tests

- driver_scripts/setup_ice_shelves.py
@JeremyFyke would like to use these for correlation with
atmospheric forcing in each basin.
> Add IMBIE basins to ice-shelf driver

- plot_features.py
Also, adjust standard figure size, dpi and some plotting properties for transects
> Fix plotting of points

- README.md
- docs/environment.yml
- readthedocs.yml
> Add support for Read The Docs

- geometric_features/feature_collection.py
Progress is not shown by default.
This progress is showing up in MPAS-Analysis runs that create the MOC regions, and it isn't convenient in that context because it does not go to a log file and instead interrupts the task progress bar.
> Suppress progress bar in differencing features

- README.md
- geometric_features/docs/parse_quick_start.py
> Update documentation link

- travis_ci/test_and_publish_docs.bash
Just so the CI finishes cleanly
> Check for empty commit

- docs/versions.rst
- geometric_features/__init__.py
- recipe/meta.yaml
> Update to v0.1.9

- docs/versions.rst
- geometric_features/__init__.py
- recipe/build.sh
- recipe/conda_build_config.yaml
- recipe/meta.yaml
Update the conda recipe -- we always include the data with the package now.
> Update to v0.1.10

- docs/versions.rst
- geometric_features/__init__.py
- recipe/meta.yaml
Bump version number for next release.
> Update to v0.1.11

- recipe/meta.yaml
> Add six as dependency

- docs/aggregation.rst
- docs/api.rst
- docs/feature_collection.rst
- geometric_features/aggregation/ocean/__init__.py
- geometric_features/aggregation/ocean/arctic_regions.py
- geometric_features/aggregation/ocean/transport_transects.py
- geometric_features/aggregation/seaice/__init__.py
- geometric_features/aggregation/seaice/arctic_regions.py
This merge adds aggregation functions for Arctic regions that are relevant to both ocean and sea-ice.
I also included clean-up in 2 places I discovered along the way, removing one irrelevant comment and fixing a typo.
> Add Arctic region aggregation for ocean and sea ice

- docs/versions.rst
- geometric_features/__init__.py
- recipe/meta.yaml
> Update to v0.1.13

- docs/versions.rst
- geometric_features/__init__.py
- recipe/meta.yaml
> Update to v0.2.0

- docs/aggregation.rst
- docs/api.rst
- docs/versions.rst
- geometric_features/__init__.py
- recipe/meta.yaml
Also add some documentation that was missed in #163.
> Update to v0.3.0

- geometric_data/ocean/transect/Barents_Sea_Opening/transect.geojson
- geometric_data/ocean/transect/Bering_Strait/transect.geojson
- geometric_data/ocean/transect/Davis_Strait/transect.geojson
- geometric_data/ocean/transect/Fram_Strait/transect.geojson
- geometric_data/ocean/transect/Lancaster_Sound/transect.geojson
- geometric_data/ocean/transect/Nares_Strait/transect.geojson
Sorry, I had forgotten one commit in #166.
> Add arctic_sections tag from forgotten commit

- geometric_data/landice/region/northWestGreenland2_oceanExtended/region.geojson
- geometric_data/landice/region/westCentralGreenland1_oceanExtended/region.geojson
Some feature names and tags were incorrect.
> Fix ocean extended features

- geometric_features/aggregation/ocean/ice_shelf_regions.py
- geometric_features/aggregation/ocean/ocean_basins.py
> Remove prints in aggregation
