merge_features.py

This merge adds groupName as an attribute on a features file. This
allows multiple feature files to be pass into a feature parsing tool
with each file having a name.

Add groupName for features

---

plot_features.py

A number of plotting problems are fixed by first mapping coordinates
from lon/lat to projection coordinates and then plotting, rather than
using the latlon argument to the basemap plot routine.
Added some output so users are aware of what is being plotted and
get a sense of how long it will take.

Fix plotting issues by mapping from lon/lat manually

---

plot_features.py

Several projections were producing artifacts when shapes were out of bounds of the projection.  This merge fixes this issue by detecting out-of-bounds points and setting them to NaN.
This merge makes several other enhancements that improve speed and functionality of the plotting script:
* Plotting has been reorganized so one Basemap object is created per projection, not one per projection per feature
* Edges of features that are longer than 1 degree are broken into a series of 1-degree segments for better plotting
* For projections that handle them correctly, features are plotted as translucent polygons as well as outlines
* Each projection is saved to a separate file with the projection name appended to the end of the file name. Four subplots in a single figure was typically too small to …

Modify plotting script to remove out-of-bounds artifacts

---

README.md
plot_features.py

This limits the types of projections that can be used but has the very large advantage that it supports polygons for a wider variety of projections and handles boundaries correctly.
(Cartophy also does a reasonable job of subdividing lines during projection, though I left in code for subdividing segments longer than 4 degrees, which results in smoother projections.)

Change plot_features to use cartophy

---

ocean/region/Global_Ocean_65N_to_65S/region.geojson

This feature is useful for comparison with observational ocean heat content.

Add feature Global Ocean 65N to 65S

---

merge_features.py

This merge updates the merge_features.py script to only recognize
geojson files, which allows other files to exist within the ocean
directory and this script will ignore them.

Update merge_features.py to only recognize geojson files

---

driver_scripts/setup_basins.py

This merge adds a script that can be used to generate the 6 major ocean basins: Atlantic, Pacific, Indian, Mediterranean, Southern Ocean and Arctic.
Optionally, with the --plot flag, the results can be plotted.

Add a script for setting up 6 ocean basins

---

difference_features.py
utils/feature_write_utils.py

This merge modifies the difference_features.py script to handle cases where:
1. a feature does not intersect the mask at all (so nothing should happen)
2. a feature intersects the mask completely so it should be removed entirely.
Features already in features.geojson are now retained but the mask is not applied to these features, only to those being added.
Also, a missing `import sys` is added to a utils script.

Fix several issues with difference_features.py

---

fix_features_at_prime_meridian.py

The script splits polygons (or multi-polygons) into a west and an east half at the prime meridian (lon=0) to make the features compatible with coordinate systems that run from 0 to 360 instead of -180 to 180.

Add script for splitting features at prime meridian

---

landice/region/Antarctica_IMBIE24/region.geojson
landice/region/Antarctica_IMBIE25/region.geojson
landice/region/Antarctica_IMBIE26/region.geojson
landice/region/Antarctica_IMBIE27/region.geojson

Fixes the tag "AntarticPeninsulaIMBIE", where peninsula was previously spelled with a double n.

Fix typo Penninsula --> Peninsula in landice tag

---

utils/feature_write_utils.py

This ensures that all properties of a feature are preserved when merging
/ splitting them between feature files.

Add preservation of all properties in a feature

---

ocean/point/Equatorial_Pacific_E145.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_E155.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_E165.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_E175.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W090.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W095.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W105.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W115.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W125.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W135.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W145.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N02.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N04.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N06.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N08.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N10.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_S02.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_S04.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_S06.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_S08.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_S10.0/point.geojson
ocean/point/Equatorial_Pacific_W165.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W175.0_N00.0/point.geojson
ocean/point/Southern_Ocean_Drake_Passage_W070.0_S55.0/point.geojson
ocean/point/Southern_Ocean_Drake_Passage_W070.0_S60.0/point.geojson
ocean/point/Southern_Ocean_Drake_Passage_W070.0_S65.0/point.geojson

This merge adds some standard ocean point locations which can be used
as either seed locations or to help get diagnostic information out of a
model.

Adding ocean point locations

---

simplify_features.py

Uses shapely's simplify command to remove redundancies in features.
The tolerance flag can be used to allow more simplification by
allowing features to move within a tolerance.  This may be appropriate,
for example, if the shape was adapted from a contour of a dataset on
a grid (e.g. the Bedmap2 land coverage masks).

Add simplify_features script

---

README.md
contributors/CONTRIBUTORS.md
contributors/CONTRIBUTORS_HEADER
contributors/list_contributors.py

We didn't cite our data source from http://www.marineregions.org/images/boundaries/IHO_crop.png.  This fixes this oversight. 
cc @akturner

Adds link to provenance for ocean regions

---

fix_features_at_antimeridian.py
fix_features_at_prime_meridian.py

This merge removes an unnecessary shift by 360 degrees in the script fix_features_at_prime_meridian.py. This behavior was added for compatibility with the 0-360 degree longitude coordinate used in MPAS-O but is no longer needed because the mask creator supports features between -180 and 180 degrees longitude by default.

Remove 360-degree shift from fix_features_at_prime_meridian.py

---

.gitignore
combine_features.py
difference_features.py
driver_scripts/setup_MOC_basins.py
driver_scripts/setup_ocean_basins.py
merge_features.py

This merge adds groupName to the merged feature files, to allow feature
groups to be created by subsequent tools.
Fixes #65

Add groupName as an attribute to merged feature files

---

ocean/point/Equatorial_Pacific_E145.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_E155.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_E165.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_E175.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W090.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W095.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W105.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W115.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W125.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W135.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W145.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N02.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N04.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N06.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N08.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_N10.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_S02.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_S04.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_S06.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_S08.0/point.geojson
ocean/point/Equatorial_Pacific_W155.0_S10.0/point.geojson
ocean/point/Equatorial_Pacific_W165.0_N00.0/point.geojson
ocean/point/Equatorial_Pacific_W175.0_N00.0/point.geojson
ocean/point/Southern_Ocean_Drake_Passage_W070.0_S55.0/point.geojson
ocean/point/Southern_Ocean_Drake_Passage_W070.0_S60.0/point.geojson
ocean/point/Southern_Ocean_Drake_Passage_W070.0_S65.0/point.geojson

This tag is used to find seed points for the "flood fill" operation
used to make sure the ocean is a single, connected body when setting
up MPAS-Ocean `global_ocean` test cases.
Adding this tag will make it possible to add ocean points that are
not necessarily in the ocean domain for all model configurations.
For example, points below ice shelves would not be in the ocean
domain for setups without ice-shelf cavities.

Add 'seed_point' tag to all ocean points

---

split_features.py
utils/feature_write_utils.py
utils/ioprovenance.py

This merge provenances features files, e.g.,
``` bash
$ ./tag_features.py -f ocean/region/North_Atlantic_Ocean/region.geojson -t test -o tester.geojson
$ head -n 12 tester.geojson
{
"type": "FeatureCollection", 
"features": [
{
"type": "Feature", 
"properties": {
"name": "North Atlantic Ocean", 
"tags": "North_Atlantic_Ocean;Atlantic_Basin;test", 
"object": "region", 
"component": "ocean", 
"author": "http://www.marineregions.org/downloads.php#iho", 
"history": "09/29/16 15:47 : hostname : pwolfram : /Users/pwolfram/Documents/MPAS_pull_requests/provenance_features : 2bf4bf8 : ./tag_features.py -f ocean/region/North_Atlantic_Ocean/region.geojson -t test -o tester.geojson;"
```
This will better keep track of operations performed on features files.
cc @xylar and #62

Provenances features via new history property

---

driver_scripts/setup_ocean_region_groups.py

This is to fix a small bug in setup_ocean_region_groups where the Global ocean region Global_65S_65N was included in the MOCBasinsGroup rather than in the oceanBasinsGroup.

Moved Global_65S_65N from MOCBasins to oceanBasins

---

driver_scripts/setup_ice_shelves.py

This driver merges together regions to make up 100 individual ice shelves (some of which are divided into multiple region files because they cross several IMBIE basins) and 6 analysis regions (currently: Antarctica, Peninsula, West Antarctica, East Antarctica, Filchner-Ronne and Ross).
The resulting file can be used to create masks for computing ice-shelf time series for individual ice shelves.

Add driver script for merging ice-shelf features

---

driver_scripts/setup_ocean_standard_transport_sections.py
feature_creation_scripts/transport_transects/transport_sections.m
ocean/transect/Africa-Ant/transect.geojson
ocean/transect/Agulhas/transect.geojson
ocean/transect/Antilles_Inflow/transect.geojson
ocean/transect/Bering_Strait/transect.geojson
ocean/transect/Drake_Passage/transect.geojson
ocean/transect/Florida-Bahamas/transect.geojson
ocean/transect/Florida-Cuba/transect.geojson
ocean/transect/Fram_Strait/transect.geojson
ocean/transect/Indonesian_Throughflow/transect.geojson
ocean/transect/Lancaster_Sound/transect.geojson
ocean/transect/Mona_Passage/transect.geojson
ocean/transect/Mozambique_Channel/transect.geojson
ocean/transect/Robeson_Channel/transect.geojson
ocean/transect/Tasmania-Ant/transect.geojson
ocean/transect/Windward_Passage/transect.geojson

Also adds a script that was originally used to create the sections (for provenance) and a driver script for merging the features together into a region group based on their common tag.

Add standard transect sections

---

ocean/transect/English_Channel_Deepen/transect.geojson

When creating the V3 mesh, the English Channel was closed on the
EC60to30 mesh. I drew a line by hand through the middle of the English
Channel. This version was used to make the current EC60to30V3 mesh, so
really needs to be in this geometric features repo with these points.
Note that the middle commit with 15m was used for the meshes made in
spring of 2017.  We changed it to 120m here to be more realistic.

Add English Channel Deepen

---

driver_scripts/setup_extended_antarctic_basins.py

Add an optional argument, 'extended_shelves', to existing
setup_antarctic_basins.py driver script so that extended ice shelf areas
in iceshelves regions files are included in basin region definitions.

WIP: add extended shelf option to Ant. basins driver

---

ocean/transect/Antarctic_Peninsula/transect.geojson
ocean/transect/Nares_Strait/transect.geojson
ocean/transect/White_Sea/transect.geojson

These features are needed for the CONUS grid in E3SM and perhaps for future versions of our EC60to30 and similar lower resolution meshes.

Add the two new critical passages and one "critical land blockage"

---

combine_features.py
difference_features.py
docs/adding_features.rst
fix_features_at_antimeridian.py
geometric_features/__main__.py
merge_features.py
plot_features.py
set_group_name.py
simplify_features.py
split_features.py
tag_features.py

Fix an incorrect help string in merge_features
Add back stubs for all entry points. This makes it easier to access the entry points when running
from a local git repo.

Update documentation for adding new features

---

README.md

Was pointing to `develop`, not `latest`.

Fix the badge for the docs

---

geometric_data/ocean/transect/Baja_CA_blockage/transect.geojson
geometric_features/features_and_tags.json

In some low-resolution meshes, we can get a hole through Baja. This will prevent that.

Add Baja California critical blockage

---

geometric_data/ocean/transect/Ireland_North_Channel_Deepen/transect.geojson
geometric_data/ocean/transect/Japan_Hokkaido_blockage/transect.geojson
geometric_data/ocean/transect/Japan_La_Perouse_Strait_Deepen/transect.geojson
geometric_data/ocean/transect/Japan_Tsugaru_Strait_Deepen/transect.geojson
geometric_data/ocean/transect/Japan_blockage/transect.geojson
geometric_data/ocean/transect/Sakhalin_blockage/transect.geojson
geometric_features/features_and_tags.json

We get strange channels in Japan when these are not specified. Ireland is sometimes connected to England, which could be bad.

Add Japan Ireland passages and blockages

---

geometric_features/__main__.py
geometric_features/feature_collection.py

Previous attempts to fix this didn't work out but this fix does seem to fix the tests.

fix matplotlib import when no xwindows

---

geometric_features/feature_collection.py

Without this dictionary entry, the resulting feature is not recognized, e.g., by geojsion.io.

Add missing 'type' key to combined features

---

README.md
geometric_features/geometric_features.py

This is the default location to look for geometric data if it is set.  The ability to set this variable will enable optionally packaging the data with the conda package.

Add GEOMETRIC_DATA_DIR environment variable

---

recipe/meta.yaml

It was coming from the release, rather than the current version.

Fix the recipe path

---

geometric_data/ocean/transect/Black_Sea_Blockage/transect.geojson
geometric_features/__init__.py
geometric_features/features_and_tags.json
recipe/meta.yaml

This feature makes sure that the Black Sea is not included in MPAS meshes (as long as they use critical passages and critical land blockages, which high resolution meshes typically do not).

Add Black Sea blockage

---

docs/index.rst
docs/versions.rst

Now that we have separate docs for 0.1.7, it makes sense to have a link to it.  From now on, adding a link like this should be part of every release.

Add versions page do docs

---

docs/versions.rst
geometric_features/__init__.py
geometric_features/__main__.py
recipe/meta.yaml

Previously, `merge_features` was using `./geometric_data` as the default geometry cache.  But with change to supporting a conda package version with the data included, the default is changed to the package's version of the data if available and `./geometric_data` only if not.  Thus, data is not downloaded if it is already available.
Update to v0.1.8.

Fix merge_features to use package data by default

---

geometric_features/geometric_features.py

This merge removes characters that are sometimes problematic from the directory names of features.
This merge also fixes some incorrect docstrings, adding a missing component and correcting the use of tags for reading features.

Remove problematic characters from feature dirs

---

docs/api.rst
docs/feature_collection.rst
docs/geometric_data.rst
geometric_features/__init__.py
geometric_features/feature_collection.py
geometric_features/geometric_features.py
geometric_features/test/test_set_group_name.py

Some missing references to BedMachine are added.
Several functions are added to `__init__.py` so they can be referenced more concisely in the documentation.
The autogenerated API is updated to use shorter names that skip module names.  This will also facilitate better cross-referencing using `intersphinx` (e.g. in MPAS-Tools).

Simplify and update the documentation

---

docs/aggregation.rst
docs/api.rst
geometric_features/aggregation/ocean/__init__.py
geometric_features/aggregation/ocean/antarctic_regions.py
geometric_features/aggregation/ocean/ice_shelf_regions.py
geometric_features/aggregation/ocean/moc_basins.py
geometric_features/aggregation/ocean/ocean_basins.py
geometric_features/aggregation/ocean/subbasin_regions.py
geometric_features/aggregation/ocean/transport_transects.py

This merge adds aggregation for:
* Antarctic regions
* Ocean basins
* Ice shelves
* Transport transects
* MOC basins

Add more feature aggregation

---

docs/versions.rst
geometric_features/__init__.py
recipe/meta.yaml

Getting ready for the next release.

Update to v0.1.12

---

README.md

It was referring to the wrong branch.

Fix Azure badge in README

---

geometric_features/aggregation/__init__.py

This function will be used by MPAS-Analysis and `compass` to get the features in a region and make mask files.  The function has been moved from MPAS-Analysis to `geometric_features` so it can be shared with `compass`.  It is important that the same aggregation process and also the same date stamps are used by both packages.

Add a function to get aggregation regions by name

---

geometric_features/features_and_tags.json

This fixes the features database. No review necessary.
I have tested with:
`./merge_features.py --cache geometric_data/ -c ocean -b transect -t arctic_sections -o arcticSections.geojson`
`./merge_features.py --cache geometric_data/ -c ocean -b transect -t "standard_transport_sections" -o standardTransportSections.geojson`
and both work fine.

Fix database

---

geometric_features/aggregation/__init__.py

The MOC basins are given a date stamp like other regions.  This will also make it easier to make masks for them in the same way we make other region masks.

Add MOC Basins to aggregation by name

---

geometric_features/aggregation/__init__.py

New transport transects were added, so new masks will need to be generated with a new `geometric_features` release.

Update transport transects date

---

geometric_features/feature_collection.py

The output is confusing if there is no context, so it has been removed unless `show_progress = True`.

Only print info on masked features if requested

---

README.md
azure-pipelines.yml
ci/python3.9.yaml
dev_environment.yaml
docs/build_docs.rst
docs/conf.py
geometric_features/download.py
recipe/meta.yaml

Update the README and other docs to reflect the new method for creating a development environment.
Remove some outdated documentation on getting an environment with the geometric data (this is now always included).
Remove six and alphabetize dependencies.
Update CI from py 3.6 to 3.9

Add yaml file for creating a dev environment 

---

docs/versions.rst
geometric_features/__init__.py
geometric_features/aggregation/__init__.py
geometric_features/aggregation/ocean/moc_basins.py
recipe/meta.yaml

This is the new default "Atlantic" MOC region, and the version
that includes the Mediterranean is now "AtlanticMed".
This merge updates the date stamp for the `mocBasins` aggregator
to today's date.
This merge also updates the `geometric_features` version number to 0.5.0, in anticipation of a release immediately after this PR.

 Add Atlantic MOC without Mediterranean

---

examples/setup_ocean_region_groups.py
feature_creation_scripts/extract_bedmachine_coastlines/extract_bedmachine_coastlines.py
feature_creation_scripts/extract_bedmap2_ice_coverage/extract_bedmap2_ice_coverage.py
geometric_features/aggregation/ocean/moc_basins.py
geometric_features/feature_collection.py

`cascaded_union` was deprecated in the latest release of `shapely`.
This merge also fixes some python 2 print statements in affected files.

Replace cascaded_union with unary_union

---

geometric_features/aggregation/ocean/moc_basins.py

Shapely will soon stop allowing `MultiPolygon` objects to be treated as lists, so we want to use the `.geoms` property for this purpose instead.

Fix deprecation warning in MOC aggregator

---

azure-pipelines.yml
dev-spec.txt
geometric_features/docs/parse_quick_start.py

A recent merge (#178) didn't build the docs but Azure passed even so.
This merge adds checks for errors to Azure, quitting if errors occur.
It also switches to `mamba` for building and installing the package to speed things up.
Finally, this merge replaces the `m2r` package with the `m2r2` package.  The former is no longer being maintained and isn't compatible with the newest version of its dependencies.

Fix an issue with the docs and with Azure building the docs

---

geometric_features/plot.py

Correct way of iterating over polygons in a `MultiPolygon` is with its `.geoms` attribute.

Fix deprecation error from shapely

---

docs/versions.rst
geometric_features/__init__.py
recipe/meta.yaml

While the changes in this release aren't major, it seems like it's time to consider this package to be "released" and have a real version number.

Update to v1.0.0

---

azure-pipelines.yml
geometric_data/ocean/point/Equatorial_Pacific_W090.0_N00.0/point.geojson
geometric_data/ocean/point/Southern_Ocean_Drake_Passage_W070.0_S55.0/point.geojson
geometric_features/features_and_tags.json

This merge removes ocean seed points near Tierra Del Fuego and the Galapagos Islands.  These seed points are in danger of ending up as an isolated lake in many meshes, so it is not a safe seed point for flood filling the ocean to ensure connectivity.
The Tierra Del Fuego point has caused problems in MPAS-Analysis with the SO12to60 mesh (without ice-shelf cavities).

Remove seed points near islands

---

azure-pipelines.yml
ci/python3.12.yaml
geometric_features/test/__init__.py

It seems we weren't testing with python 3.12 here and some issues have arisen on conda-forge when trying to run the test with python 3.12 there:
https://github.com/conda-forge/geometric_features-feedstock/pull/31

Fix issues with python 3.12 

---

geometric_data/ocean/transect/Carroll_Inlet/transect.geojson
geometric_features/features_and_tags.json

This feature keeps access to Carroll Inlet adjacent to Stange Ice Shelf in the Bellingshausen Sea region of Antarctica.

Add Carroll Inlet as a critical passage

---

README.md
recipe/build.sh

In this PR I added a few flags to the `python -m pip install [-e] .` command. The flags are:
* `-vv` indicates very verbose output. This flag is used during the CI runs to help with debugging.
* `--no-deps` indicates that pip should not install runtime dependencies from PyPi.
* `--no-build-isolation` indicates that pip should not install build time dependencies from PyPi.

Add flags to `pip install` command

---

.github/dependabot.yml

This PR adds the dependabot workflow. Dependabot checks for updates to dependencies on a weekly basis, and makes a PR when an update is available.

Add dependabot workflow to auto-update dependencies

---

docs/conf.py

This PR just removes an old fix where we were blacklisting sphinx-multiversion version 1.7.2. We no longer need to do so, so I've removed that bit. I also fixed a small typo in the same file.

Whitelist all sphinx-multiversion versions

---

.github/workflows/build_workflow.yml
.github/workflows/pre_commit_update_workflow.yml

This adds a GitHub actions workflow that will run the `pre-commit autoupdate` command to update `pre-commit` and its dependencies. The workflow is set to run weekly on Wednesdays and should automatically create a pull request with the updates when they are available. 
I also included a small fix for the build workflow, which will hopefully stop failed tests from canceling other tests (to isolate bugs associated with a particular python version, for instance).

Add CI workflow to automatically update pre-commit and its dependencies

---

geometric_data/seaice/region/April_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/August_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/December_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/February_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/January_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/July_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/June_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/March_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/May_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/November_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/October_Historical_Median_Sea_Ice_Extent/region.geojson
geometric_data/seaice/region/September_Historical_Median_Sea_Ice_Extent/region.geojson

The name of the feature needs to be exactly the same as the folder it's in (except ' ' --> '_') and the name of the component needs to be `seaice` instead of `sea ice`.

Fix sea-ice historical median features

---

geometric_features/features_and_tags.json
geometric_features/test/test_features_and_tags.py
geometric_features/utils.py

This test generates a new `features_and_tags.json` based on the contents of `geometric_data`.
The contents of `geometric_features/features_and_tags.json` have been updated with the correct data produced with:
`geometric_features.utils.write_feature_names_and_tags()`.

Add test to make sure `features_and_tags.json` looks as expected

---

.github/workflows/build_workflow.yml
geometric_features/aggregation/__init__.py
geometric_features/aggregation/landice/nasa_greenland_extended.py
geometric_features/aggregation/seaice/historical_sea_ice.py
geometric_features/feature_collection.py
geometric_features/plot.py
geometric_features/test/test_aggregation.py
geometric_features/test/test_feature_collection.py
geometric_features/test/test_features_and_tags.py
geometric_features/test/test_geometric_features.py
geometric_features/utils.py

This merge addresses all the lint identified by `flake8` within the `geometric_features` package.  Notably, it doesn't address the `feature_creation_scripts` directory, which is there for provenance and we don't necessarily try to keep it clean or up-to-date.

Fix `flake8` lint in `geometric_features`

---

dev-spec.txt
geometric_features/test/test_features_and_tags.py
recipe/meta.yaml

We need to find `geometric_features/features_and_tags.json` using
`importlib.resources` and we want to store the comparison file
in the temporary directory generated for the test, not the current
directory.
This merge also removes `imortlib_requests`, which is included in all supported versions of python.

Fix test_features_and_tags 

---

.github/workflows/build_workflow.yml
.github/workflows/pre_commit_update_workflow.yml

This PR updates the build workflow to use separate directories for each python version for conda caching. Issues with this seem to have been crashing CI runs lately.
I also set the pre-commit autoupdate workflow to use the same `PYTHON_VERSION` convention as the docs workflow, for consistency.

Use separate conda cache directories in CI

---

.pre-commit-config.yaml

The `pre-commit` hook used to be `ruff` but it changed to `ruff-check`, resulting in a message about the legacy alias. This updates the hook to the current `ruff-check` format.

Change `pre-commit` hook ID to `ruff-check`

---

.github/workflows/pre_commit_update_workflow.yml

This PR implements a two-token solution that fixes the permissions errors we're seeing with the pre-commit update job. 
Additionally, it simplifies environment setup, improving compatibility, and enhancing automation of pull request creation and management. The workflow now uses a standard Python setup instead of Conda/Micromamba, ensures the correct reviewers and labels are added, and handles existing pull requests more robustly.

Implement two-token method in pre-commit CI

---

.github/workflows/pre_commit_update_workflow.yml

This pull request makes a minor update to the pre-commit update workflow configuration. The change removes the automatic assignment of reviewers when creating pull requests for pre-commit dependency updates.

Fix pre-commit update action (again)
